### ISSUE TITLE
MQTT broker password 

### ISSUE THREAD

**Issue by zamzon** [dingusdk/ihcmqttgateway#1]
Hi
If my broker requires a user and password to connect, how do I type this into the ihcmqttgateway.conf

**Comment by dingusdk** [comment]
Mqtt Username and password was not included, but I have added it now. 

I do not have a mqtt broker setup to use username/password, so if you can confirm it is actually working that would be nice.

**Comment by zamzon** [comment]
could you make a compiled version ? I don't have a compiler

**Comment by dingusdk** [comment]
I have compiled a binary you can download here:

https://www.dingus.dk/download/ihcmqttgateway/IhcMqttGateway1.0.1.zip

(The link in the orginal post at dingus.dk has also been updated)

**Comment by zamzon** [comment]
I can´t get it working.

```
My exe file shows:
IhcMqttGateway 1.0.0 (c) 2017 J.Ø.N. Dingus.dk
Connectiong to ihc controller: http://192.168.0.200
Authentication succecfull
Conneting to MQTT
Subscribe to MQTT
READY  (press 'q' to exit)

```
My conf file:

```
`IhcUrl http://192.168.0.200
IhcUser admin
IhcPassword admin
MqttHost 192.168.0.103
#MqttUsername openhabian
#MqttPassword 1234

## how should boolean true and false be represented in MQTT
BooleanFalse 0
BooleanTrue 1

# Confugure MQTT topics one line for each ihc resource id
# The syntax for in, out or inout is:
# resourceid <- topic
# resourceid -> topic
# resourceid <-> topic
# Use in or out if your want to define only one direction or if you want to 
# have different topic for each direction.
# Use inout <-> if you want to use the same topic for both in and out

# Examples
2400859 <- ihctest1
8795230 -> ihctest2
9048926 <-> ihctest3`


```

I subscribe to the following topics

ihctest1
ihctest2
ihctest3

**Comment by dingusdk** [comment]
You have commented out the MqttUSername and MQttPassword - remove the #

Meanwhile I have setup a username password on my own mqtt broker, and it is working fine. 
(There is no error handling if the mqtt connection fails so you will not be notified. )

**Comment by zamzon** [comment]
Thx it works now.
Do you have any plans to integrate wireless dimmers, temperature/humidity sensor and timers in the future.?

**Comment by dingusdk** [comment]
You already have it - it is not only working for boolean (on/off) resource, you can also link to ihc resources for integer numbers (light level) and floating point (temperature/humidity). 

I will close this now - as the original password issue is solved. If you have further comments/questions please do it on the post on my blog about the ihc mqtt gateway:

http://www.dingus.dk/ihc-mqtt-gateway/
